<?php
define('DB_HOST','localhost');
define('DB_USER','root');
define('DB_PASSWORD','');
define('DB_NAME','jaiguruji');
/*define('DB_HOST','mysql9.000webhost.com');
define('DB_USER','a4951095_shaurya');
define('DB_PASSWORD','sam.db');
define('DB_NAME','a4951095_guruji');*/
?>